# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dab4ff4423fb1c7e5b055a93c5dfa5b14a9fafc317b070c9406822c00d84bcdd9bab827d951ecf591c9e820a06e26ff532ddc70d7d5737813018e8874e005ad

test:
  secret_key_base: 28361c00966c1d5eb604252968ffed48949cd1fa639590a47c02583b1e94a8d3e506f8f7a4880672bcc33d1c74610e186d0c82b0e2d13fe16b102a2de316a40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
